package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LocaltransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaltransferAllPropertiesEquals(Localtransfer expected, Localtransfer actual) {
        assertLocaltransferAutoGeneratedPropertiesEquals(expected, actual);
        assertLocaltransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaltransferAllUpdatablePropertiesEquals(Localtransfer expected, Localtransfer actual) {
        assertLocaltransferUpdatableFieldsEquals(expected, actual);
        assertLocaltransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaltransferAutoGeneratedPropertiesEquals(Localtransfer expected, Localtransfer actual) {
        assertThat(expected)
            .as("Verify Localtransfer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaltransferUpdatableFieldsEquals(Localtransfer expected, Localtransfer actual) {
        assertThat(expected)
            .as("Verify Localtransfer relevant properties")
            .satisfies(e ->
                assertThat(e.getSenderAccountNumber()).as("check senderAccountNumber").isEqualTo(actual.getSenderAccountNumber())
            )
            .satisfies(e ->
                assertThat(e.getRecipientAccountNumber()).as("check recipientAccountNumber").isEqualTo(actual.getRecipientAccountNumber())
            )
            .satisfies(e -> assertThat(e.getRecipientBankName()).as("check recipientBankName").isEqualTo(actual.getRecipientBankName()))
            .satisfies(e ->
                assertThat(e.getRecipientBankBranch()).as("check recipientBankBranch").isEqualTo(actual.getRecipientBankBranch())
            )
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getTransactionDate()).as("check transactionDate").isEqualTo(actual.getTransactionDate()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocaltransferUpdatableRelationshipsEquals(Localtransfer expected, Localtransfer actual) {
        assertThat(expected)
            .as("Verify Localtransfer relationships")
            .satisfies(e -> assertThat(e.getBankAccount()).as("check bankAccount").isEqualTo(actual.getBankAccount()));
    }
}
